# Branch diseases {#branchdis}

## Botryosphaeria cankers {-}

### *Diplodia agrifolia*, *D. corticola*, *D. quercina*, *Dothiorella iberica* and others {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

----------------- 2025. Botryosphaeria cankers. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

## Orange hobnail canker {-}

### *Cryphonectria gyrosa* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. Orange hobnail canker. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

## Oak mistletoe  {-}

### *Phoradendron villosum* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. Oak mistletoe.  In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.
