# Branch and trunk diseases {#branchtrunkdis}

## Insect-pathogen complexes {-}

### Foamy bark canker {-}

#### *Geosmithia* sp. 42 {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

------------------- 2025. Foamy bark canker. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

### Fusarium dieback {-}

#### *Fusarium*  {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

------------ 2025. Fusarium dieback. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

## Diseases affecting bark and sapwood {-}

### Bacterial canker of oak / "Acute oak decline" {-}

#### *Brennaria*, *Lonsdalea* , ... species  {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

--------------. 2025. Bacterial canker of oak / "Acute oak decline". In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

## Botryosphaeria cankers {-}

### *Diplodia agrifolia*, *D. corticola*, *D. quercina*, *Dothiorella iberica*, and others {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

----------------- 2025. Botryosphaeria cankers. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.


### Sudden oak death and Phytophthora stem cankers {-}

#### *Phytophthora ramorum*, *P. nemorosa*, *P. pseudosyringae* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. Sudden oak death and Phytophthora stem cankers. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

### Sunscald {-}

#### Abiotic {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. Sunscald. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.



### Wetwood {-}

#### Various bacteria and fungi {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. Wetwood. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.


## Canker-associated wood decay fungi {-}


### *Annulohypoxylon thouarsianum* {-}


#### Distribution / Hosts {-}


#### Symptoms {-}


#### Agent Description {-}


#### Biology {-}


#### Importance {-}


#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. *Annulohypoxylon thouarsianum*. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

### *Biscogniauxia mediterranea* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

--------------- 2025. *Biscogniauxia mediterranea*. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.


### Canker rots {-}

#### *Inonotus andersonii*, *Inocutis dryophila* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. Canker rots. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

## Orange hobnail canker {-}

### *Cryphonectria gyrosa* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. Orange hobnail canker. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.


## Other wood decay fungi {-}

### Hedgehog fungus {-}

#### *Hericium erinaceus* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. Hedgehog fungus. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

### Western sulfur shelf fungus {-}

#### *Laetiporus gilbertsonii* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. Western sulfur shelf fungus. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.


### *Fomitiporia robusta* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. *Fomitiporia robusta*. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

 

### *Phellinus gilvus* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. *Phellinus gilvus*. In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.

## Parasitic vascular plants {-}

### Oak mistletoe  {-}

#### *Phoradendron villosum* {-}


#### Distribution / Hosts {-}



#### Symptoms {-}



#### Agent Description {-}



#### Biology {-}



#### Importance {-}



#### Citation {-}

Swiecki, T.J.; Bernhardt, E.A. 2025. Oak mistletoe.  In Swiecki, T.J., et al. (Eds.) Field Guide to Insects and Diseases of California Oaks, Online edition 2025.





