# General foliar feeders {-}

## California oakworm, California oakmoth - *Phryganidia californica* (Dioptidae) {-}

### Distribution / Hosts {-}



### Symptoms {-}



### Agent Description {-}



### Biology {-}



### Importance {-}

## Tent caterpillars (Lasiocampidae): Western tent caterpillar - *Malacosoma californicum*, Pacific tent caterpillar - *M. constrictum*, Forest tent caterpillar - *M. disstria* {-}

### Distribution / Hosts {-}



### Symptoms {-}



### Agent Description {-}



### Biology {-}



### Importance {-}

## Western tussock moth - *Orgyia vetusta* (Lymantriidae) {-}

### Distribution / Hosts {-}



### Symptoms {-}



### Agent Description {-}



### Biology {-}



### Importance {-}

## Fruit tree leafroller - *Archips argyrospila* (Tortricidae) and others {-}

### Distribution / Hosts {-}



### Symptoms {-}



### Agent Description {-}



### Biology {-}



### Importance {-}

## Oak ribbed casemaker - *Bucculatrix albertiella* (Lyonetiidae) {-}

### Distribution / Hosts {-}



### Symptoms {-}



### Agent Description {-}



### Biology {-}



### Importance {-}

